# Change Source: Autoware 30-point implementation request | Date: 2026-04-07
FROM ros:humble-ros-base

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-colcon-common-extensions \
    python3-vcstool \
    ros-humble-ament-lint \
    ros-humble-ament-lint-auto \
    ros-humble-ament-lint-common \
    ros-humble-ros2bag \
    git \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

CMD ["bash"]
